AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  ApiName:
    Description: Name of the API
    Type: String
    Default: nss

Resources:
  DynamoDBStreamSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Join ['', [!Ref ApiName, '-dynamoDB-stream-topic']]

  DynamoDBStreamSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref DynamoDBStreamSNSTopic
      Endpoint: !ImportValue
        'Fn::Sub': '${ApiName}-stream-queue-arn'
      Protocol: sqs
      RawMessageDelivery: 'true'

  SNSToSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !ImportValue
          'Fn::Sub': '${ApiName}-stream-queue-url'
      PolicyDocument:
        Statement:
          Action:
            - sqs:SendMessage
          Effect: Allow
          Principal: '*'
          Resource: !ImportValue
            'Fn::Sub': '${ApiName}-stream-queue-arn'
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref DynamoDBStreamSNSTopic

Outputs:

  DynamoDBStreamSNSTopicArn:
    Description: DynamoDB Stream SNS topic ARN
    Value: !Ref DynamoDBStreamSNSTopic
    Export:
      Name: !Join [ '', [!Ref ApiName, '-dynamoDB-stream-sns-topic-arn']]

  DynamoDBStreamSNSTopicName:
    Description: DynamoDB Stream SNS topic name
    Value: !GetAtt DynamoDBStreamSNSTopic.TopicName
    Export:
      Name: !Join [ '', [!Ref ApiName, '-dynamoDB-stream-sns-topic-name']]

